meta:
  name: MWDB
  description: Malware repository for automated malware collection and analysis systems.

settings:
  apikey: "null"
# temp api key included for testing. Will be removed for final build.
