---

statusStyle: "dot"

background:
  image: /images/background44.jpg


favicon: /images/favicon.png

title: Cyber Threat Reporting Platform

cardBlur: xl  # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur

hideVersion: true

theme: dark

color: slate

useEqualHeights: true
disableCollapse: true



layout:
  Reporting:
    style: column
    columns: 2


  Reference:
    style: column
    columns: 2

  Evidence Analysis:
    style: column
    columns: 2

  Evidence Collection:
    style: column
    columns: 2

  Documentation & Administration:
    style: row
    columns: 4

  Threat News:
    style: row
    columns: 2

