version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:2.21.4
    container_name: portainer
    restart: always
#    ports:
#      - "8000:8000"
#      - "9443:9443"
    command: --admin-password '$$2y$$05$$ZBq/7oanDzs4iwkhQCxF2uKoJsGXA0SI4jdu1PkFrnsKfpCH5Ae4G' #changed during deployment
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

    networks:
        - docker_underserved
  
  helper-reset-password:
    image: portainer/helper-reset-password


volumes:
  portainer_data:

networks:
    docker_underserved:
      external: true
