version: '3'

services:
    misp_forms:
        build:
          context: .
        restart: always
        ports:
          - 5000:5000
        networks:
            - docker_underserved
networks:
  docker_underserved:
    external: true
